#!/usr/bin/env bash
set -e # halt script on error

bundle exec jekyll build
bundle exec htmlproof ./_site --alt-ignore "/.*/" --check-html --disable-external --file-ignore "/.+\/documentation\/.+/"

grep -o 'http://www.microsoft.com/[^"]*' ./vsto-redirect.html | xargs curl -s | grep -o -c "Visual Studio 2010 Tools for Office Runtime" || {
    echo "ERROR: fail to verify the VSTO runtime download link. Please update the link in vsto-redirect.html"
    exit 2
}
